scheduler:
  interval_seconds: 86400   # run every 24 hours

workspace:
  id: "Team 23"

team:
  id: "team1"
  agents:
    - name: "agent8"

export:
  time_window:  ## This has to be calculated on fly from interval seconds.
    from: "2026-01-16"
    to: "2026-01-20"
  output_dir: "exports"

models:
  - "@openai/gpt-4o-mini"
  - "@openai/gpt-4o"
  - "@bedrock/us.meta.llama3-1-70b-instruct-v1:0"
  - "@openai/gpt-3.5-turbo-0125"

agents:
  agent8:
    description: >
      Generates personalized marketing email copy for XYZ(Fintech) company campaigns.
    system_prompt_for_runners: prompts/campaign_copy_generator_system.txt
    judge:
      provider: portkey
      model: "@openai/gpt-4o-mini"
      temperature: 0
      prompt_file: prompts/campaign_copy_generator_evaluator.txt

  agent11:
    description: >
      Answer employee questions about HR policies, benefits, procedures, and provide guidance on HR processes
    system_prompt_for_runners: prompts/hr_ops_agent_system.txt
    judge:
      provider: portkey
      model: "@openai/gpt-4o-mini"
      temperature: 0
      prompt_file: prompts/hr_ops_agent_evaluator.txt
